#!/bin/bash
#
#  install_server2_key: install ssh key for dem@hull-Lenovo-3000-G550
#
#      Jon Hull -- 10/13/16
#

key="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCxOQXHQWYi5FOjEdnNUpAozTcilWlcRGhewJjWwkGCznUBGkWFxJjerToyOJT8XhWngzXLJ2pFvnsyO7mOCJz+A089ELioWJSXNCnHxoewcSc0t0h2TVddtXBhdeXfJRlUTW9z9oYIGtGsIWzpGLasiMuCGOOG0Grs1kIN/nyQDn8VKfeEIOnfuLeFtsKEhCcTyuwrZD5rJM7UUF4WepYThR4RvwjSim0eeZ/46bfsxbA1x+pRRgycquEeJXZXdpQyEiIlco5IJeBNv9U3cebKOh9ueqXbbCQMgax6ZFv87/bEkBWAUQeqGER3Dz0r8xwhXS/LPIElmLu3gm5qWxSD dem@hull-Lenovo-3000-G550"

echo `/bin/date` " start: installing ssh key for dem@hull-Lenovo-3000-G550"

cd /home/dem

if [ ! -d .ssh ]; then
   mkdir .ssh
   /bin/chown dem .ssh
   /bin/chgrp dem .ssh
   cat /dev/null > .ssh/authorized_keys
fi

cd .ssh

grep "dem@hull-Lenovo-3000-G550" authorized_keys > /dev/null

if [ $? -eq 0 ];
  then
    echo `/bin/date` " ssh key already here. authorized_keys not modified"
  else
    echo `/bin/date` " ssh key for dem@hull-Lenovo-3000-G550 added to authorized_keys"
    echo $key >> authorized_keys
    /bin/chown dem authorized_keys
    /bin/chgrp dem authorized_keys
fi

echo `/bin/date` " finished: installing ssh key for dem@hull-Lenovo-3000-G550"
