#!/bin/bash
#
#  install_pkgs:  install various packages and updates.
#    To add more packages, add a script that installs the package.
#    Each script should check to make sure it doesn't install
#    redundant copies of its package.
#
#       Jon Hull -- 10/5/16
#
echo `/bin/date` " : start installing packages"

/usr/local/bin/install_ssh

let mach_num=`/usr/local/bin/echo_host`
echo "machine_num=" $mach_num

if [ $mach_num -ge 22 ] && [ $mach_num -le 25 ]; then
   /usr/local/bin/install_smartmontools
   /usr/local/bin/install_JSON
   # /usr/local/bin/install_flashplugin
fi

echo `/bin/date` " : finished installing packages"
