#!/bin/bash
#
#  install_server_key: install ssh key for dem@dvcserver
#
#      Jon Hull -- 10/13/16
#

key="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC/0hN8THT7a3ZsYwamAmkUa8y8RUrN4TFKftN4eGETWdNIMTD/LmdGVZ4XbgYQ1A9yp6DmOOkYY1ETlZilfy266oeUGjBcaKQ/ybFMBeVzUV/Tkh0Oa4nbtrn8H66wEXWJJBSIDf+NKG9IouuYoGKWD/Ll6vrxTkRVwtAzsT6U/6tulx02rqKIhMlhuNdU+9Aor0DtQGnguwr75LQ+kOLuQhNbbEh1MH85wl5yjNfp67dBYIPpFFn40vwXH/f9t4Vn2tkJ1oIo2J92v8RvWo6AndS3boA0YiuNjeTZGHX1ZE/Om0a3370lmJkdksoQfoqG64wPcXBwe2UQBppbT5e3 dem@dvc-dell-57"

echo `/bin/date` " start: installing ssh key for dem@dvc-dell-57"

cd /home/dem/.ssh

grep "dem@dvc-dell-57" authorized_keys > /dev/null

if [ $? -eq 0 ];
  then
    echo `/bin/date` " ssh key already here. authorized_keys not modified"
  else
    echo `/bin/date` " ssh key for dem@dvcserver being added to authorized_keys"
    echo $key >> authorized_keys
    /bin/chown dem authorized_keys
    /bin/chgrp dem authorized_keys
fi

echo `/bin/date` " finished: installing ssh key for dem@dvcserver"
