#!/bin/bash
#
#  install_JSON: install JSON package in perl
#
#      Jon Hull -- 10/5/16
#

echo `/bin/date` " start: installing JSON package in perl"

let install_status=`dpkg -s libjson-perl|grep Status|awk 'BEGIN { stat=0;} (/install ok installed/) { stat=1;} END {print stat;}'`

if [ $install_status -eq 1 ]; then
  echo `/bin/date` " JSON package already up to date"
  exit 0
fi

apt-get -y install libjson-perl

echo `/bin/date` " finished: installing JSON package in perl"
